"""phone number changed

Revision ID: 29abf722d1d3
Revises: 560883d35da8
Create Date: 2023-09-21 20:03:48.101488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29abf722d1d3'
down_revision: Union[str, None] = '560883d35da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('role', sa.String(), nullable=True))
    op.drop_column('profiles', 'phone_number')
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    op.add_column('profiles', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profiles', 'role')
    # ### end Alembic commands ###
